equipej
Union-CRM/spa pull request #6
Opened 2023-01-30 19:34 UTC by DiegoLabarewski

equipej

2023-01-30 19:58 UTC, kaerealarcon requested changes
Comentário 01 src/App.js - Quando for subir o src/App.js, matém ele limpo, apenas com o import da home no máximo, assim evita conflitos de merge

Comentário 02 src/components/PlannerCard/clients.jsx - Acrescentar mais 4 itens para testar o scroll

Comentário 03 Planner Card - Separar os componentes de dentro do PlannerCard em pastas, seguindo o padrão de manter o Index.jsx e Style.jsx agrupados

2023-01-30 19:58 UTC, kaerealarcon commented on src/components/PlannerCard/clientes.jsx
> +
Acrescentar mais 4 itens para testar o scroll

2023-01-30 19:58 UTC, kaerealarcon commented on src/App.js
> +            <Route path="/PlannerCard" element={<PlannerCard />} />
Quando for subir o src/App.js, matém ele limpo, apenas com o import da home no máximo, assim evita conflitos de merge

2023-02-01 19:05 UTC, DiegoLabarewski commented
Criação da PlannerCard

2023-02-03 12:23 UTC, closed without merging

2023-02-03 12:24 UTC, kaerealarcon commented
Fechado devido a tempo em que está em aberto, problema já foi corrigido em pull request posterior