SubjectCard
Union-CRM/spa pull request #7
Opened 2023-01-30 21:06 UTC by CarlosHideki

SubjectCard

2023-01-31 20:37 UTC, CarlosHideki commented
Update

2023-02-01 14:08 UTC, Heder-Silva-Oliveira requested changes

2023-02-01 14:08 UTC, Heder-Silva-Oliveira commented on src/components/SubjectCardListView/CardListView/index.jsx
> +import {ReactComponent as Edit} from '../../../assets/Edit.svg'
Melhoria: Adicionar os novos ícones do icon system

2023-02-01 19:07 UTC, Heder-Silva-Oliveira approved these changes

2023-02-01 19:07 UTC, merged